### ISSUE TITLE
Port StringExtensions and TestCaseNameParser utilities

### ISSUE THREAD

**Issue by codito** [spekt/testlogger#1]

**Comment by Siphonophora** [comment]
I should have time to pull this stuff in over the weekend. Are we still going to need the string extensions if we are using the name parser?

**Comment by codito** [comment]
Great, appreciate any help. Yes, we may need StringExtensions. E.g. `ReplaceInvalidXmlChar` is used by loggers for normalizing text for xml.

**Comment by codito** [comment]
Ported `TestCaseNameParser` with c2cdd59. Will port StringExtensions shortly.

**Comment by Siphonophora** [comment]
@codito Hey, just browsing the updates. Let me know if there is anything you would like me to work on.

**Comment by codito** [comment]
@Siphonophora the core is ready to be integrated with loggers. We've a PR for nunit here: https://github.com/spekt/nunit.testlogger/pull/74. I'm working on a similar integration for `xunit` too. `junit` integration is up for grabs :)

**Comment by Siphonophora** [comment]
Great. I will take a look at the nunit one and will do the junit integration.
