### ISSUE TITLE
Add adapter detection and port xunit/nunit specific implementations

### ISSUE THREAD

**Issue by codito** [spekt/testlogger#3]
We've junit logger users who use xUnit, Nunit and MSTest adapters. Each of these adapters have custom ways to represent framework properties in `TestResult` or `Message`. Example of issues:

* https://github.com/spekt/junit.testlogger/issues/11
* https://github.com/spekt/junit.testlogger/issues/14
* https://github.com/spekt/junit.testlogger/issues/15

Can we build some abstractions around adapter specific primitives? This will enable the loggers to simply use `TestResultInfo` to serialize results to their formats.

Known differences

* xUnit emits messages with specific prefix. See https://github.com/spekt/xunit.testlogger/blob/master/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L323
* xUnit may have different notion of result outputs. See https://github.com/spekt/xunit.testlogger/blob/master/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L279

**Comment by codito** [comment]
For design ideas, please see https://github.com/spekt/testlogger/pull/9#issuecomment-696725704 and https://github.com/spekt/testlogger/pull/9#issuecomment-696840147.

**Comment by Siphonophora** [comment]
Found a junit user who is using mstest. https://github.com/TASVideos/BizHawk

**Comment by codito** [comment]
Adapter detection is added with c2cdd59. Next task here is to add the xunit specific implementation along with tests.

**Comment by codito** [comment]
xunit implementation added with https://github.com/spekt/testlogger/commit/80686725d477bb1326e0a61857fc522eb9f7587a
