### ISSUE TITLE
Publish test's display name

### ISSUE THREAD

**Issue by tamaratomilova** [spekt/testlogger#34]
Related to this issue in junit.testlogger https://github.com/spekt/junit.testlogger/issues/57

The property was removed a few month ago in this commit https://github.com/spekt/testlogger/commit/8c0973b07efe6f4038f4c42bc1306e577333da02

PS. I actually wanted to create a PR for this, but unfortunately have no permission to create a branch - is it so that only known contributors can do that?

**Comment by codito** [comment]
@tamaratomilova thank you reporting. Please fork this repo, fix in local branch in the fork and create a pull request for `master` branch in this repo.

Will be glad to accept a PR for this.

**Comment by codito** [comment]
Closing this in favor of https://github.com/spekt/junit.testlogger/issues/57. Please share any feedback on https://github.com/spekt/junit.testlogger/issues/57#issuecomment-1620547408
