### ISSUE TITLE
Problem with TestCaseNameParser.cs

### ISSUE THREAD

**Issue by marc-delhoune** [spekt/testlogger#35]
Hi,

If the name of a test (namespace, class, of method) contains a zero (0), the new TestCaseNameParser.cs fails.
The MethodRegex and ClassDataRegex check for [a-z1-9_.], so they do not allow a zero.  Should this be [a-z0-9_.] instead?

Using 'Parser=Legacy' solves my problem for now.

Best regards,

Marcus

**Comment by Siphonophora** [comment]
@marc-delhoune Thanks for reporting this. yes `0` should be allowed. We will work on getting the fix pushed out for this. Which logger are you using?

**Comment by marc-delhoune** [comment]
I was using XunitTestAdapter.

**Comment by codito** [comment]
Pushed testlogger v3.0.86 to all logger and cut a release in nuget. /cc: @Siphonophora
