### ISSUE TITLE
Design notes

### ISSUE THREAD

**Issue by codito** [spekt/testlogger#4]
What goes in this library?
* Common utilities across all loggers
* Adapter specific handling

Design notes
* Provide a base logger to deal with Microsoft.TestPlatform.ObjectModel contracts
* A thin data abstraction for downstream logger implementations
* Contract for serializer. Idea is downstream loggers only need to implement a serializer for their own formats

**Comment by Siphonophora** [comment]
For the base logger, is this everything we need to provide?:

* Provide an abstract InitializeSettings method that can be overridden (but doesn't need to be) to process additional settings, beyond the path and file name. 

*  Provide an abstract string CreateLogContents(List<TestResultInfo> resultList) that should return the log file contents. 

* Should FriendlyName and ExtensionUri be abstract get only properties?


Also, I briefly looked at the Microsoft loggers. This seems like a good time to pull in some of their functionality if we are missing anything. I don't see anything obvious, but wanted to see if you had any ideas.

**Comment by codito** [comment]
I had similar ideas about the APIs. Will spend some more time on this over the weekend.

**Comment by Siphonophora** [comment]
@codito I just pushed to a branch with the ported string extensions, and also included a roughed out version of the base logger. I think this is more or less what we want as a starting point. Let me know what you think. 

I also pushed https://github.com/spekt/junit.testlogger/tree/UseTestLoggerBase which uses the base logger. It builds but mostly it fails acceptance testing.

**Comment by codito** [comment]
@Siphonophora thank you. I am away for a few weeks, will take a look when I am back.

**Comment by codito** [comment]
First cut of the design is up for review: https://github.com/spekt/testlogger/pull/9

**Comment by codito** [comment]
Fixed with cfd1fc6
